llm:
  repo_id: TheRains/Qwen2.5-14B-Instruct-Q4_K_M-GGUF
  name: qwen2.5-14b-instruct-q4_k_m.gguf
  n_ctx: 8192

clip_like:
  name: google/siglip2-large-patch16-384
  batch_size: 24
  embedding_dim: 1024

vision:
  name: facebook/dinov2-with-registers-large
  batch_size: 40
  embedding_dim: 1024