defaults:
  - models: default
  - model_roles: default
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

root: ??
device: null

hydra:
  run:
    dir: .
  output_subdir: null
